### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#170]
The project runs locally but the `docker build webapp` fails when deploying 

```
remote: yarn run v1.22.4        
remote: $ react-app-rewired build        
remote: Setting NODE_PATH to resolve modules absolutely has been deprecated in favor of setting baseUrl in jsconfig.json (or tsconfig.json if you are using TypeScript) and will be removed in a future major release of create-react-app.        
remote: 
remote: Creating an optimized production build...        
remote: Failed to compile.        
remote: 
remote: ./src/components/LacchainSetNodeInfoActionInfoField.js        
remote: Attempted import error: 'ArrayTextField' is not exported from '@eoscostarica/eoscr-components'.        
remote: 
remote: 
remote: error Command failed with exit code 1.        
remote: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.        
remote: The command '/bin/sh -c yarn build' returned a non-zero code: 1        
```

**Comment by xavier506** [comment]
![image](https://user-images.githubusercontent.com/5632966/97792817-1b842480-1ba9-11eb-92d2-e48ef8cd3069.png)

**Comment by adriexnet** [comment]
We did an update in @eoscostarica/eoscr-components a couple of days ago to add the ArrayTextField and now the version 3.1.0 export it so I tried to fix the error updating the yarn.lock but I get the same error when the action run but the build in my local works, I think that it could be related to some kind of cache maybe with the node_modules folder, package.json or yarn.lock or maybe the eosio-dashboard-deployer-test docker image that still are using an old version and produce the error

**Comment by xavier506** [comment]
I ran `docker build -t eosio-dashboard-deployer-test --no-cache `

still fails to complie:

```
remote: Creating an optimized production build...        
remote: Failed to compile.        
remote: 
remote: ./src/components/LacchainSetNodeInfoActionInfoField.js        
remote: Attempted import error: 'ArrayTextField' is not exported from '@eoscostarica/eoscr-components'.        
remote: 
remote: 
remote: error Command failed with exit code 1.        
remote: info Visit https://yarnpkg.com/en/docs/cli/run for 
```

Are there any other changes that may be affecting hoe dependencies are managed ? TS?

**Comment by adriexnet** [comment]
Did you run it in your local?

**Comment by xavier506** [comment]
i ran it in the github workflow

https://github.com/eoscostarica/eosio-dashboard/runs/1338603339?check_suite_focus=true

**Comment by kuronosec** [comment]
@xavier506 the eosio-dashboard-deployer is not really related to this problem, it just calls the build process, that its actually executed in the k8s master.
