### ISSUE TITLE
Nodes not appearing on map

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#172]
Node info has been uploaded but they are not appearing on map

![image](https://user-images.githubusercontent.com/5632966/97794426-82143d00-1bbf-11eb-8648-70012535b468.png)

**Comment by adriexnet** [comment]
how long ago was it updated? The current backend process will update the bpjson and nodes info each 24h because we are not displaying real-time info from the blockchain, we have a databas table that works as a cache with the producer info and the bpJson that it's updated each 24 hours

**Comment by xavier506** [comment]
This was updated several days ago. It appears it is not updating data from the nodes table
