### ISSUE TITLE
Add node name hover to cpu and missed blocks graph

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#195]
It is hard to tell which node is the one missing blocks

![image](https://user-images.githubusercontent.com/5632966/98494334-5a962380-2202-11eb-91ce-34b2bf98ae92.png)

**Comment by murillojorge** [comment]
Please take a look at proposed design and comments for this section: https://www.figma.com/file/ygnXQx6DFQZ9GQdKOttDpF/EOS-Dashboard?node-id=133%3A0

Zeplin specs here: https://zpl.io/aBrkEBQ

**Comment by adriexnet** [comment]
Hi @murillojorge @xavier506 I also added the time in the tooltip, do you agree or prefer to delete it?

![image](https://user-images.githubusercontent.com/5375168/101015268-c1220f00-352c-11eb-93a7-eab8c54240c1.png)
