### ISSUE TITLE
Show account name when logged in

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#211]
The login module can be updated to indicate when a user has an active session by displaying the name of the account that is logged in. 

This is how we handled user sessions in the UI before switching to the new theme.

![image](https://user-images.githubusercontent.com/5632966/99159319-f7dcd600-26a0-11eb-8dc0-ed36de402cdc.png)

**Comment by murillojorge** [comment]
Updated header can be found here: https://zpl.io/a7rmA4v
