### ISSUE TITLE
Improve footer mention of eoscr

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#224]
Lets change the existing text for 

An [open source](https://guide.eoscostarica.io/docs/open-source-guidelines) project by [EOS Costa Rica](https://eoscostarica.io)

The link font color should be black , same as text color, on mouse over hover style should be underline and cursor should change

Existing text: 
![image](https://user-images.githubusercontent.com/5632966/99198385-d68def80-275d-11eb-9e86-cb4bff48acc0.png)

**Comment by murillojorge** [comment]
Please refer to: https://zpl.io/bJMzDm6
