### ISSUE TITLE
Add descriptive paragraphs

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#225]
Users can use a bit of text to help guide them on the dashboard features.

![image](https://user-images.githubusercontent.com/5632966/99198414-18b73100-275e-11eb-8874-ba88ac5b572c.png)

## Accounts Page

Enter a valid EOSIO account name to see information on the account and also interact with any smart contract deployed on that account.

## Rewards Distributon

**Comment by murillojorge** [comment]
Let's use a collapsible read more component for this issue. It should be available for all pages, but only if we have copy for them. Check it out: https://zpl.io/2jyZr4p
Now it would be nice if @ldrojas could help us out with the copy.Thanks.

**Comment by murillojorge** [comment]
<img width="1637" alt="Screen Shot 2021-07-13 at 11 18 28" src="https://user-images.githubusercontent.com/1179619/125497036-f4d56c4f-3fe7-4fdf-ac9c-42e06d8dd19a.png">
