### ISSUE TITLE
replace favicon

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#229]
favicon is too small and indistinguishable lets use our websites favicon and get some more brand recognition 

https://eoscostarica.io/img/favicon.ico

**Comment by xavier506** [comment]
@murillojorge  lets get different versions of the favicon

**Comment by murillojorge** [comment]
Here's the favicon complete package: https://drive.google.com/file/d/1aBDWt0SreDCCB1w0cUoV_YSMuAUBanVd/view?usp=sharing
