### ISSUE TITLE
TX per Sec & TX per block graphs

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#335]
Lets convert these to line graphs

Take a look at this: https://zpl.io/aX0O64g

**Comment by xavier506** [comment]
![image](https://user-images.githubusercontent.com/5632966/114937429-07507e80-9dfb-11eb-9378-d00e0cb5c520.png)

**Comment by murillojorge** [comment]
Let's specify breakpoints.
