### ISSUE TITLE
Block Producer cards redesign implementation

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/eosio-dashboard#345]
We need to review the design for this cards so the info is properly oriented, grouped and understandable.

![image](https://user-images.githubusercontent.com/5632966/114937695-58607280-9dfb-11eb-9696-97c535c7303e.png)

**Comment by xavier506** [comment]
I think there should be between 25-50 Block producers per page

**Comment by murillojorge** [comment]
The card designs can be found here: https://zpl.io/am35nxv
