### ISSUE TITLE
account creator not working

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#398]
If I create an account using the form provided i cant find it after , if i create an account using the accounts tool i can find it later

![image](https://user-images.githubusercontent.com/5632966/115305425-860f2980-a123-11eb-96ff-8c8be52db997.png)

As a lacchain partner i should not have to enter the creator name as it should be the account i am logged in with

![image](https://user-images.githubusercontent.com/5632966/114926501-a66e7980-9ded-11eb-8d26-cf36c61e0f9c.png)

**Comment by xavier506** [comment]
I am unable to create an account using this form 

![Uploading image.png…]()

**Comment by adriexnet** [comment]
@xavier506 I tested it yesterday and it's working fine, please take  a look to the attached video 

https://user-images.githubusercontent.com/5375168/115746567-a9b7b700-a351-11eb-9718-06fc441f9974.mov
