### ISSUE TITLE
Nodes Cards Implementation

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#400]
Cards for different node types in lacchain 

Node Types:

- Validator 
- Boot
- Writer
- Oberserver

![image](https://user-images.githubusercontent.com/5632966/114939423-a4acb200-9dfd-11eb-8c62-35ef95e94711.png)

**Comment by murillojorge** [comment]
New version for the cards can be found here: https://zpl.io/am35nxv
