### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#436]
Set number of records per page and browse between pages

**Comment by xavier506** [comment]
@adriexnet  do table rows have pagination here?

![image](https://user-images.githubusercontent.com/5632966/116954788-2601a280-ac4e-11eb-95cb-b94327d28bdd.png)

**Comment by murillojorge** [comment]
Let's use this component: https://zpl.io/aX7AGnX
Refer to this frame: https://zpl.io/V4NpAEy
