### ISSUE TITLE
default network logo

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#437]
### Nodes
![image](https://user-images.githubusercontent.com/5632966/116502413-ac923a80-a870-11eb-8755-df2934964c60.png)

### BP schedule
![image](https://user-images.githubusercontent.com/5632966/116502372-92f0f300-a870-11eb-8e7a-5a8c463f0712.png)

**Comment by murillojorge** [comment]
@xavier506 what do you think of something like this?
![1-2-2 Dashboard - Entities](https://user-images.githubusercontent.com/1179619/117043927-0d839d80-accb-11eb-977f-4399d7b0870b.png)

**Comment by murillojorge** [comment]
Assets can be found here: https://zpl.io/29mRr0W

**Comment by xavier506** [comment]
@tetogomez 

let's replace any latamlink logo with lacchain logo

**Comment by murillojorge** [comment]
@tetogomez this are the logos to use: https://zpl.io/29mRr0W
Grey for not found or default logos, and colored for the main selector logos.
