### ISSUE TITLE
writer node not showing

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#446]
The node `writer.cr` is not showing on the dashboard , despite bing registered on the blockchain 

![image](https://user-images.githubusercontent.com/5632966/116948635-2b0a2600-ac3d-11eb-9300-9f8ba659bb86.png)

You can verify the node records with the following command 

`cleos -u https://writer.eosio.cr get table eosio eosio node -L wirter.cr --limit 1`

**Comment by adriexnet** [comment]
@xavier506 I take a look to this issue and looks that the writer it's not avialable in the node table

**Comment by xavier506** [comment]
@adriexnet  did you take a look at this? 

`cleos -u https://writer.eosio.cr get table eosio eosio node -L wirter.cr --limit 1`


is there a limit to the number of records shown?
