### ISSUE TITLE
Link TX to block explorer

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#484]
Link TX success message to block explorer

https://explorer.latamlink.io/transaction/4e709707673fb2f4c6544e4084291a2e05a8aa60ef59d79b73f941305c764547

![image](https://user-images.githubusercontent.com/5632966/118078016-84c3cc00-b372-11eb-8f11-12af2a0c6ad3.png)

**Comment by murillojorge** [comment]
Something like this, with a timer so users know what's going on: https://zpl.io/V0oO8Zw
