### ISSUE TITLE
Add Jungle Testnet Logo

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#558]
We should use this logo: 

To set NETWORK Logo for Jungle Testnet

`REACT_APP_EOS_API_NETWORK_LOGO=https://jungletestnet.io/assets/jungle-testnet-logo.png`|

![image](https://user-images.githubusercontent.com/5632966/120110172-ba660480-c129-11eb-81dd-9c018e14d001.png)

@murillojorge  Lets edit this image to obtain the ideal logo for the dashboard

**Comment by murillojorge** [comment]
Let's use this.
![jungle-256](https://user-images.githubusercontent.com/1179619/120689480-62007100-c461-11eb-8091-ef527165cabc.png)
![jungle-1080](https://user-images.githubusercontent.com/1179619/120689481-63319e00-c461-11eb-8a37-66ba7d9c1e5f.png)
