### ISSUE TITLE
Cards Order

### ISSUE THREAD

**Issue by adriexnet** [eoscostarica/eosio-dashboard#575]
## LACCHAIN ORDER
- TPS All Time High
- Network Utilization All Time High
- Transactions Last Hour
- Transactions Last Day
- Transactions Daily Average
- Transactions Last Week
- Total Entities
- Partner Entities
- Non-Partner Entities
- Total Nodes
- Validator Nodes
- Boot Nodes
- Writer Nodes
- Observer Nodes
- Unique Locations
- CPU Limit Per Block
- Net Limit Per Block
- Chain CPU Limit
- Chain Net Limit

## MAINNET ORDER

- Total BPs Registered
- Total Nodes
- Producer Nodes
- Full Nodes
- Query Nodes
- Seed Nodes
- Query, Seed Nodes
- Unknown Nodes
- Unique Locations
- CPU Limit Per Block
- Net Limit Per Block
- Chain CPU Limit
- Chain Net Limit

**Comment by xavier506** [comment]
@tetogomez  included order for cards
