### ISSUE TITLE
Read more descriptions

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#645]
### Home Page 

 - Blockchain consensus group 
 - transactions  per second and per block 
 - general overview and network stat

### Entities / Block Producers

Blockchain accounts that have registered to run nodes on the network , their information is gather from on chain tables and their bp.json files

### Nodes 

Actual nodeos instances that are run by a particular entity for different node types along with  their specific information such as endpoints and location.

### API Endpoints

Public API endpoints provided by node operators on the netowrk

## Remove Help Text from :

- About 
- Help

**Comment by ldrojas** [comment]
@xavier506 / @AngeloCG97 
## Texts for the "read more" sections:

### Dashboard

Find data of blockchain networks using EOSIO technology. See more networks here: https://eosio.online/. 


### Entities

A list of entities part of the network. They can be partner or non-partner entities.


### Block Producers

A list of the block producers in the network – blockchain accounts registered to run nodes on the network. It includes information from chain tables and their bp.json files. 


### Nodes

A list of all the nodes run by entities comprising the network with specific information such as endpoints and location.


### API Endpoints

An updated list of public API endpoints provided by node operators in the network. 


### Network Topology

A visual representation of the network’s current nodes.


### Geo Distribution

A visualization of the geographic distribution of the nodes in this network.


### Block Distribution

A visualization of the distribution of blocks produced by the nodes in the network.


### Missed Blocks

A list of scheduled, produced, and missed blocks by each account in the network. 


### CPU Benchmarks

A visualization of CPU usage in milliseconds by block producer nodes accounts, with lowest, highest, and average usage data.


### Validator Agreement

Read more about the Validator Node Agreement of this network. Contact us if you have any inquiries. 


### Accounts and Contracts

This tool helps you seek information about network accounts and contracts. Type the name of a contract or account in the space provided to start searching. You’ll obtain the data of the contract actions, contract tables, scope, lower and upper bounds, and limits.


### Management

Log in to manage your account configurations.


### Node config

Use this tool to configure a new node in the network.
