### ISSUE TITLE
Add other resources

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#682]
Under Chain resources add a similar header called Other Resources 

![image](https://user-images.githubusercontent.com/5632966/134050924-41658477-9467-4e01-b425-8be0d218dbf8.png)

This will be a bulleted  list of URLs from BP JSON

```
"other_resources": [
			"https://mainnet.eosio.online",
			"https://eosrate.io",
			"https://guide.eoscostarica.io",
			"https://guias.eoscostarica.io",
			"https://evodex.io"
		],
```

**Comment by murillojorge** [comment]
Hey @adriexnet please use this design as reference. https://zpl.io/aX7By8M
