### ISSUE TITLE
Improve UI from the main page 

### ISSUE THREAD

**Issue by Mike3563** [eoscostarica/eosio-dashboard#861]
Les't changes the footer, sidebar and header from the dashboard.

- [x] Footer
- [x] Header
- [x] Sidebard

**Comment by fvives99** [comment]
- [ ] remove version string from sidebar anda dd to footer (right side)
- [ ] move footer links to the right side
- [ ] add link to github bug report to right side
- [ ] change made with x message
- [ ] leave github repo only on footer
- [ ] telegram can possibly go in the footer also
