### ISSUE TITLE
Wrong network endpoints

### ISSUE THREAD

**Issue by leisterfrancisco** [eoscostarica/eosio-dashboard#890]
On `proton testnet`, node endpoints are wrong. Endpoints are pointing to mainnet when they should be pointing to `proton testnet`.

![image](https://user-images.githubusercontent.com/28828796/189511904-ea5b842e-fcf2-4b3b-9d10-26f83b0456ed.png)

**Comment by xavier506** [comment]
are we propoerly ready the `chains.json` file ?

maybe we can have a health check to make sure bp.json file provided is correct

**Comment by adriexnet** [comment]
@xavier506 @leisterfrancisco In this case the BP producer dont have a valid record for proton testnet you can take a look at https://greymass.com/chains.json so we are loading the data from https://greymass.com/bp.json as a fallback, we can change that to avoid load a default bp.json but if we dont load any bp josn we will not able to display branding, location, social and other basic information that are usually shared between all the networks

**Comment by Mike3563** [comment]
Lets take advantage of this issue to check how often we refresh bpjson data
